---
title: "Calidad del agua superficial en el territorio mexicano"
author: "Jimena Pedroza & Tamara Guerrero"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bg: "#101010"
      fg: "#FDF7F7" 
      primary: "#ED79F9"
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(dplyr)
library(leaflet)
library(ggplot2)
library(readxl)

df_superficial <- read_excel("Calidad_del_Agua_Superficial_a.xlsx")
```

```{r}
# Convertimos SEMAFORO y ESTADO a factor
df_superficial$SEMAFORO <- as.factor(df_superficial$SEMAFORO)
df_superficial$ESTADO <- as.factor(df_superficial$ESTADO)
```

Column
-----------------------------------------------------------------------

### Resumen

El agua subterránea es dulce, se encuentra bajo la superficie del suelo, almacenada en acuíferos, estas reservas son de gran importancia, ya que en épocas de sequías son los únicos suministros que se poseen. Con respecto al agua subterránea, México tiene definidos 653 acuíferos y el 38.7% del agua utilizada en el país proviene de estas fuentes.

### Indicadores generales

```{r}
#Total de sitios
valueBox(nrow(df_superficial), icon = "fa-tint", color = "lightblue", caption = "Sitios monitoreados")
```

Column
-----------------------------------------------------------------------

### Indicadores generales

```{r}
#Total de cuencas
valueBox(value = length(unique(df_superficial$CUENCA)), icon = "fa-mountain", color = "lightgreen", caption = "Cuencas monitoreadas")
```

Column
-----------------------------------------------------------------------

```{r}
# Porcentaje de sitios con semáforo rojo
porc_rojo <- round(mean(df_superficial$SEMAFORO == "Rojo") * 100)
valueBox(porc_rojo, icon = "fa-exclamation-triangle", color = "red", caption = "% Semáforo Rojo")

# Porcentaje de sitios con semáforo amarillo
porc_amarillo <- round(mean(df_superficial$SEMAFORO == "Amarillo") * 100)
valueBox(porc_amarillo, icon = "fa-exclamation-circle", color = "orange", caption = "% Semáforo Amarillo")

# Porcentaje de sitios con semáforo verde
porc_verde <- round(mean(df_superficial$SEMAFORO == "Verde") * 100)
valueBox(porc_verde, icon = "fa-check-circle", color = "green", caption = "% Semáforo Verde")
```

Row
-----------------------------------------------------------------------

### Mapa interactivo de calidad del agua

```{r}
df_superficial$SEMAFORO <- factor(df_superficial$SEMAFORO,
                                  levels = c("Verde", "Amarillo", "Rojo"))

# Paleta de colores por semáforo
paleta_semaforo <- colorFactor(
  palette = c("green", "orange", "red"),
  levels = c("Verde", "Amarillo", "Rojo")
)

# Etiquetas personalizadas
etiquetas_semaforo <- c("Verde" = "Aceptable",
                        "Amarillo" = "Contaminada",
                        "Rojo" = "Muy contaminada")

# Mapa
leaflet(df_superficial) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addCircleMarkers(
    lng = ~LONGITUD,
    lat = ~LATITUD,
    color = ~paleta_semaforo(SEMAFORO),
    radius = 4,
    stroke = FALSE,
    fillOpacity = 0.7,
    popup = ~paste0("<strong>", SITIO, "</strong><br>",
                    "Estado: ", ESTADO, "<br>",
                    "Semáforo: ", etiquetas_semaforo[SEMAFORO])
  ) %>%
  addLegend(
  position = "bottomright",
  colors = c("green", "orange", "red"),
  labels = c("Aceptable", "Contaminada", "Muy contaminada"),
  title = "Semáforo de calidad",
  opacity = 1
)

```

Column
-----------------------------------------------------------------------

### Contaminantes más frecuentes

```{r}
# Procesamos la columna de contaminantes
contaminantes <- df_superficial %>%
  filter(!is.na(CONTAMINANTES)) %>%
  pull(CONTAMINANTES) %>%
  strsplit(split = ",") %>%
  unlist() %>%
  trimws() %>%
  as.data.frame()

colnames(contaminantes) <- "Contaminante"

# Contar frecuencia
frecuencia <- contaminantes %>%
  group_by(Contaminante) %>%
  summarise(Frecuencia = n()) %>%
  arrange(desc(Frecuencia)) %>%
  top_n(10, Frecuencia)

# Graficar
plot_ly(frecuencia,
        x = ~reorder(Contaminante, Frecuencia),
        y = ~Frecuencia,
        type = 'bar',
        orientation = 'v',
        marker = list(color = "pink")) %>%
  layout(title = "Top 8 contaminantes más frecuentes",
         xaxis = list(title = "Contaminante"),
         yaxis = list(title = "Frecuencia"),
         margin = list(b = 100))
```

